import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/themeContext";
import Provider from "@/context/provider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const Lang = cookieStore.get("lang");
  const Direction = cookieStore.get("direction");

  const language = Lang ? Lang.value : "en";
  const direction = Direction ? Direction.value : "ltr";

  return (
     <html
        lang={language}
        className={inter.className}
        dir={direction}
        suppressHydrationWarning={true}>
        <Provider lang={language}>
           <body
              className={`${inter.className} bg-white dark:bg-darkModeColor`}
              suppressHydrationWarning={true}>
              <ThemeProvider>{children}</ThemeProvider>
           </body>
        </Provider>
     </html>
  );
}
